### ISSUE TITLE
Class not generated

### ISSUE THREAD

**Issue by JulienDev** [equinox-one/symbols#1]
Hi Mateu,
Thanks for your lib which is very useful. Unfortunately classes are not generated, so I can't use it for the moment. Do I need to enable something in order to make it work? Or maybe it doesn't work yet on AS 2?
Julien

**Comment by mateuy-dev** [comment]
Symbols uses annotation processing. You may need to configure your IDE.
Maybe: https://immutables.github.io/apt.html can help.
What is AS 2?

**Comment by JulienDev** [comment]
Sorry, Android Studio 2

**Comment by mateuy-dev** [comment]
You will need this:
https://bitbucket.org/hvisser/android-apt

**Comment by JulienDev** [comment]
Awesome, it works ! Maybe you should add instructions in the readme
