### ISSUE TITLE
Usage in Android project

### ISSUE THREAD

**Issue by RoRoche** [equinox-one/symbols#3]
Hi Mateu,

I tried both:

``` groovy
    compile 'one.equinox:symbols:+'
```

and:

``` groovy
    apt 'one.equinox:symbols:+'
```

And I always get the following error:

``` groovy
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.NoSuchMethodError: com.squareup.javapoet.AnnotationSpec.get(Ljavax/lang/model/element/AnnotationMirror;)Lcom/squareup/javapoet/AnnotationSpec;
```

Can you tell me how to configure my Android project to make it use "Symbols" please?

**Edit:**
It's a Multidex project.

**Comment by mateuy-dev** [comment]
You need to use
`compile 'one.equinox:symbols:+'`

and 

```
repositories {
        jcenter()
}
```

Check also https://bitbucket.org/hvisser/android-apt

**Comment by RoRoche** [comment]
I've finally solved my issue.
It was just a bad combination with another library using `javapoet`.
I just had to exclude `javapoet` from the other dependency, using the following configuration in my `build.gradle` file:

``` groovy
{
    exclude(group: 'com.squareup', module: 'javapoet')
}
```

and include it apart:

``` groovy
compile 'com.squareup:javapoet:1.6.1'
```
